// Pemilih props eksplisit per tab/modal (Fase 3) — hook = satu sumber state,
// komponen menerima hanya yang dipakai JSX-nya.
export function pickOrders(s) {
  const { adminPackages, analytics, copied, customDomainItems, customThemesList, deletingDemos, filterPackage, filteredOrders, handleCleanupDemoData, handleOpenBlastModal, handleOpenCloneModal, items, load, mainTab, open, openWhiteLabelModal, orderTab, searchQuery, setCopied, setDemoModalOpen, setDemoSlug, setDemoSuccessSlug, setDemoThemeId, setFilterPackage, setInvoiceModalItem, setOpen, setOrderTab, setPrintCardModalItem, setSearchQuery, setSocialMockupItem, setWaModalItem } = s
  return { adminPackages, analytics, copied, customDomainItems, customThemesList, deletingDemos, filterPackage, filteredOrders, handleCleanupDemoData, handleOpenBlastModal, handleOpenCloneModal, items, load, mainTab, open, openWhiteLabelModal, orderTab, searchQuery, setCopied, setDemoModalOpen, setDemoSlug, setDemoSuccessSlug, setDemoThemeId, setFilterPackage, setInvoiceModalItem, setOpen, setOrderTab, setPrintCardModalItem, setSearchQuery, setSocialMockupItem, setWaModalItem }
}
export function pickThemes(s) {
  const { announcement, customThemesList, demoOverrides, handleDeleteCustomTheme, items, mainTab, savingAnnouncement, setAnnouncement, setEditDemoFormData, setEditDemoModalTheme, setSavingAnnouncement, setThemeSubTab, themeSubTab } = s
  return { announcement, customThemesList, demoOverrides, handleDeleteCustomTheme, items, mainTab, savingAnnouncement, setAnnouncement, setEditDemoFormData, setEditDemoModalTheme, setSavingAnnouncement, setThemeSubTab, themeSubTab }
}
export function pickMonetization(s) {
  const { adSettings, adminPackages, customDomainItems, handleAddVoucher, handleDeleteVoucher, handleSavePackages, handleSavePayment, handleUploadQris, items, load, mainTab, monetizationSubTab, newVoucherCode, newVoucherDiscount, newVoucherQuota, newVoucherType, paymentSettings, savingAds, savingPackages, savingPayment, savingVoucher, setAdSettings, setAdminPackages, setMonetizationSubTab, setNewVoucherCode, setNewVoucherDiscount, setNewVoucherQuota, setNewVoucherType, setPaymentSettings, setSavingAds, setUploadingBanner, uploadingBanner, uploadingQris, vouchersList } = s
  return { adSettings, adminPackages, customDomainItems, handleAddVoucher, handleDeleteVoucher, handleSavePackages, handleSavePayment, handleUploadQris, items, load, mainTab, monetizationSubTab, newVoucherCode, newVoucherDiscount, newVoucherQuota, newVoucherType, paymentSettings, savingAds, savingPackages, savingPayment, savingVoucher, setAdSettings, setAdminPackages, setMonetizationSubTab, setNewVoucherCode, setNewVoucherDiscount, setNewVoucherQuota, setNewVoucherType, setPaymentSettings, setSavingAds, setUploadingBanner, uploadingBanner, uploadingQris, vouchersList }
}
export function pickSystem(s) {
  const { activeWaTab, backupRestoreSummary, confirmAdminPassword, customThemesList, exportingBackup, formatWaMessage, handleChangePassword, handleDownloadBackup, handleRestoreBackupFile, handleSaveMaintenance, handleSaveProfile, handleSaveSeo, handleSaveWaTemplates, importingBackup, items, mainTab, maintenanceSettings, newAdminPassword, password, passwordMsg, platformSubTab, savingMaintenance, savingPassword, savingProfile, savingSeo, savingWaTemplates, seoSettings, setActiveWaTab, setConfirmAdminPassword, setMaintenanceSettings, setNewAdminPassword, setPlatformSubTab, setSeoSettings, setSiteProfile, setSystemSubTab, setWaTemplates, siteProfile, systemSubTab, waTemplates } = s
  return { activeWaTab, backupRestoreSummary, confirmAdminPassword, customThemesList, exportingBackup, formatWaMessage, handleChangePassword, handleDownloadBackup, handleRestoreBackupFile, handleSaveMaintenance, handleSaveProfile, handleSaveSeo, handleSaveWaTemplates, importingBackup, items, mainTab, maintenanceSettings, newAdminPassword, password, passwordMsg, platformSubTab, savingMaintenance, savingPassword, savingProfile, savingSeo, savingWaTemplates, seoSettings, setActiveWaTab, setConfirmAdminPassword, setMaintenanceSettings, setNewAdminPassword, setPlatformSubTab, setSeoSettings, setSiteProfile, setSystemSubTab, setWaTemplates, siteProfile, systemSubTab, waTemplates }
}
export function pickModals(s) {
  const { adminPackages, blastInputText, blastModalItem, blastQueue, blastSentMap, blastTemplate, cloneModalItem, cloning, customThemesList, demoGenerating, demoModalOpen, demoSlug, demoSuccessSlug, demoThemeId, editDemoFormData, editDemoModalTheme, formatWaMessage, handleCloneSubmit, handleCopyAllBlastLinks, handleGenerateBlastQueue, handleSaveWhiteLabelAdmin, handleSendNextBlast, handleSendSingleBlast, invoiceModalItem, items, load, newCloneSlug, open, openWhatsApp, printCardModalItem, savingDemoOverrideState, savingWl, setBlastInputText, setBlastModalItem, setBlastQueue, setBlastSentMap, setBlastTemplate, setCloneModalItem, setDemoGenerating, setDemoModalOpen, setDemoOverrides, setDemoSlug, setDemoSuccessSlug, setDemoThemeId, setEditDemoFormData, setEditDemoModalTheme, setInvoiceModalItem, setNewCloneSlug, setPrintCardModalItem, setSavingDemoOverrideState, setSocialMockupItem, setUploadingDemoPhoto, setWaModalItem, setWhiteLabelModalItem, setWlMode, setWlText, setWlUrl, socialMockupItem, uploadingDemoPhoto, waModalItem, whiteLabelModalItem, wlMode, wlText, wlUrl } = s
  return { adminPackages, blastInputText, blastModalItem, blastQueue, blastSentMap, blastTemplate, cloneModalItem, cloning, customThemesList, demoGenerating, demoModalOpen, demoSlug, demoSuccessSlug, demoThemeId, editDemoFormData, editDemoModalTheme, formatWaMessage, handleCloneSubmit, handleCopyAllBlastLinks, handleGenerateBlastQueue, handleSaveWhiteLabelAdmin, handleSendNextBlast, handleSendSingleBlast, invoiceModalItem, items, load, newCloneSlug, open, openWhatsApp, printCardModalItem, savingDemoOverrideState, savingWl, setBlastInputText, setBlastModalItem, setBlastQueue, setBlastSentMap, setBlastTemplate, setCloneModalItem, setDemoGenerating, setDemoModalOpen, setDemoOverrides, setDemoSlug, setDemoSuccessSlug, setDemoThemeId, setEditDemoFormData, setEditDemoModalTheme, setInvoiceModalItem, setNewCloneSlug, setPrintCardModalItem, setSavingDemoOverrideState, setSocialMockupItem, setUploadingDemoPhoto, setWaModalItem, setWhiteLabelModalItem, setWlMode, setWlText, setWlUrl, socialMockupItem, uploadingDemoPhoto, waModalItem, whiteLabelModalItem, wlMode, wlText, wlUrl }
}
