import { Crown, Cake, GraduationCap, Baby, Briefcase } from 'lucide-react'

// Universal Event Types Configuration
export const eventTypeConfigs = {
  wedding: {
    id: 'wedding',
    name: 'Pernikahan & Walimatul Urs',
    icon: Crown,
    headerBadge: 'WALIMATUL \'URS',
    coverTitle: 'The Wedding Invitation of',
    heroNames: 'Sarah & Budi',
    personTitle: 'Pasangan Mempelai',
    storyTitle: 'Cerita Kisah Cinta',
    quote: 'Dan di antara tanda-tanda kekuasaan-Nya ialah Dia menciptakan untukmu pasangan dari jenismu sendiri...',
    quoteSource: 'QS. Ar-Rum: 21',
    eventTitle1: 'Akad Nikah',
    eventTitle2: 'Resepsi Pernikahan',
    wishesTitle: 'Buku Tamu & Doa Restu',
    giftTitle: 'Wedding Gift / Amplop Digital',
    dresscodeTitle: 'Panduan Busana Resepsi',
  },
  birthday: {
    id: 'birthday',
    name: 'Ulang Tahun & Sweet 17',
    icon: Cake,
    headerBadge: 'BIRTHDAY CELEBRATION',
    coverTitle: 'You are Invited to the Birthday of',
    heroNames: 'Sarah Bella (17th)',
    personTitle: 'Bintang Ulang Tahun',
    storyTitle: '17 Tahun Penuh Kenangan Indah',
    quote: 'Merayakan 17 tahun penuh tawa, cinta keluarga, dan harapan cerah untuk masa depan.',
    quoteSource: 'Sweet Seventeen Celebration',
    eventTitle1: 'Birthday Party & Fun Games',
    eventTitle2: 'Celebration Dinner & Music',
    wishesTitle: 'Ucapan Selamat & Harapan',
    giftTitle: 'Birthday Gift / Kado Spesial',
    dresscodeTitle: 'Dresscode Pesta Ulang Tahun',
  },
  graduation: {
    id: 'graduation',
    name: 'Wisuda & Kelulusan',
    icon: GraduationCap,
    headerBadge: 'GRADUATION CEREMONY',
    coverTitle: 'Graduation Celebration of',
    heroNames: 'dr. Siti Sarah, Sp.A',
    personTitle: 'Profil Wisudawati',
    storyTitle: 'Perjalanan Meraih Gelar Dokter',
    quote: 'Perjalanan panjang penuh dedikasi dan ketekunan. Terima kasih atas doa orang tua, guru, dan sahabat.',
    quoteSource: 'Doctor of Medicine',
    eventTitle1: 'Upacara Wisuda & Sumpah',
    eventTitle2: 'Tasyakuran & Ramah Tamah',
    wishesTitle: 'Ucapan Selamat & Doa Sukses',
    giftTitle: 'Graduation Gift / Apresiasi',
    dresscodeTitle: 'Dresscode Syukuran Kelulusan',
  },
  aqiqah: {
    id: 'aqiqah',
    name: 'Aqiqah & Syukuran Bayi',
    icon: Baby,
    headerBadge: 'TASYAKURAN AQIQAH',
    coverTitle: 'Tasyakuran Kelahiran & Aqiqah',
    heroNames: 'Aruna Muhammad Al-Fatih',
    personTitle: 'Putra Tercinta',
    storyTitle: 'Arti Nama & Harapan Orang Tua',
    quote: 'Ya Allah, jadikanlah putra kami anak yang sholeh, berbakti kepada orang tua, dan bermanfaat bagi sesama.',
    quoteSource: 'Doa Syukuran Aqiqah',
    eventTitle1: 'Cukur Rambut & Tausiyah',
    eventTitle2: 'Santap Siang & Doa Bersama',
    wishesTitle: 'Doa & Ucapan untuk Si Kecil',
    giftTitle: 'Tanda Kasih Aqiqah',
    dresscodeTitle: 'Dresscode Syukuran Keluarga',
  },
  corporate: {
    id: 'corporate',
    name: 'Acara Perusahaan & Gala Dinner',
    icon: Briefcase,
    headerBadge: 'ANNUAL GALA DINNER',
    coverTitle: 'Official Invitation to',
    heroNames: 'Aruna Tech Summit 2026',
    personTitle: 'Keynote Speaker & Host',
    storyTitle: 'Tema & Visi Acara',
    quote: 'Transformasi digital menuju masa depan berkelanjutan. Bergabunglah bersama para inovator dan pemimpin industri.',
    quoteSource: 'Annual Corporate Summit',
    eventTitle1: 'Keynote Speech & Launching',
    eventTitle2: 'Gala Dinner & Awarding Night',
    wishesTitle: 'Konfirmasi Kehadiran VIP',
    giftTitle: 'Registrasi & Akses Masuk VIP',
    dresscodeTitle: 'Dresscode Bisnis Formal / Black Tie',
  },
}

// Curated Starter Presets (Zero emojis)
export const themePresets = [
  {
    name: 'Terracotta Boho',
    colors: { bg: '#FDFBF7', paper: '#F7F2EB', fg: '#2C221E', muted: '#876D61', accent: '#C86D51', accentSoft: '#F4DCD4', cover: '#2C221E' },
    opacities: { bg: 100, paper: 95, accent: 100, accentSoft: 100, cover: 70 },
    fonts: { display: '"Playfair Display", serif', script: '"Alex Brush", cursive', body: '"Plus Jakarta Sans", sans-serif', letterSpacing: '0.04em' },
    ornamentStyle: 'botanical',
    particleEffect: 'petals',
    coverStyle: 'fullscreen',
    openingAnimation: 'wax_seal',
    layoutStyle: 'side_by_side',
    coupleTransition: 'meet_middle',
    ornamentTransition: 'expand_line',
    panelTransition: 'staggered_slide',
    photoColorFilter: 'warm_vintage',
    galleryLayout: 'masonry',
    monogramStyle: 'royal_laurel',
    wishesStyle: 'floating_cards',
    dividerShape: 'arch',
    cardStyler: { borderRadius: 12, backdropBlur: 8, shadowLevel: 'soft', borderWidth: 1 },
    guestTouchFx: 'petal_burst',
    livingMotion: { floatingIntensity: 'medium', breathingBloom: true, shimmerGlow: true, entrancePhysics: 'smooth_spring' }
  },
  {
    name: 'Emerald Royalty',
    colors: { bg: '#0A1C16', paper: '#112B22', fg: '#F2EDE4', muted: '#A3B8B0', accent: '#D4AF37', accentSoft: '#385E50', cover: '#071510' },
    opacities: { bg: 100, paper: 85, accent: 100, accentSoft: 100, cover: 80 },
    fonts: { display: '"Cinzel", serif', script: '"Great Vibes", cursive', body: '"Lora", serif', letterSpacing: '0.06em' },
    ornamentStyle: 'gold_flourish',
    particleEffect: 'gold_dust',
    coverStyle: 'classic',
    openingAnimation: 'curtain',
    layoutStyle: 'stacked',
    coupleTransition: 'scale_up',
    ornamentTransition: 'glow_pulse',
    panelTransition: 'flip_3d',
    photoColorFilter: 'champagne_glow',
    galleryLayout: 'carousel',
    monogramStyle: 'victorian_crest',
    wishesStyle: 'editorial_vintage',
    dividerShape: 'crown',
    cardStyler: { borderRadius: 8, backdropBlur: 12, shadowLevel: 'dramatic_3d', borderWidth: 1 },
    guestTouchFx: 'sparkle_trail',
    livingMotion: { floatingIntensity: 'dynamic', breathingBloom: true, shimmerGlow: true, entrancePhysics: 'cinematic_slow' }
  },
  {
    name: 'Sage Serenity',
    colors: { bg: '#F4F7F4', paper: '#FFFFFF', fg: '#203328', muted: '#6D8275', accent: '#52796F', accentSoft: '#CAD2C5', cover: '#2F3E46' },
    opacities: { bg: 100, paper: 90, accent: 100, accentSoft: 100, cover: 65 },
    fonts: { display: '"Cormorant Garamond", serif', script: '"Pinyon Script", cursive', body: '"Plus Jakarta Sans", sans-serif', letterSpacing: '0.03em' },
    ornamentStyle: 'botanical',
    particleEffect: 'melati',
    coverStyle: 'arch',
    openingAnimation: 'fade',
    layoutStyle: 'arch',
    coupleTransition: 'fade_blur',
    ornamentTransition: 'unfurl',
    panelTransition: 'staggered_slide',
    photoColorFilter: 'pastel_dream',
    galleryLayout: 'grid',
    monogramStyle: 'diamond_floral',
    wishesStyle: 'floating_cards',
    dividerShape: 'wave',
    cardStyler: { borderRadius: 16, backdropBlur: 6, shadowLevel: 'soft', borderWidth: 1 },
    guestTouchFx: 'petal_burst',
    livingMotion: { floatingIntensity: 'subtle', breathingBloom: true, shimmerGlow: false, entrancePhysics: 'smooth_spring' }
  },
  {
    name: 'Midnight Vogue',
    colors: { bg: '#0F172A', paper: '#1E293B', fg: '#F8FAFC', muted: '#94A3B8', accent: '#38BDF8', accentSoft: '#0369A1', cover: '#020617' },
    opacities: { bg: 100, paper: 75, accent: 100, accentSoft: 100, cover: 75 },
    fonts: { display: '"Syne", sans-serif', script: '"Playfair Display", serif', body: '"Inter", sans-serif', letterSpacing: '0.08em' },
    ornamentStyle: 'clean_line',
    particleEffect: 'bokeh',
    coverStyle: 'fullscreen',
    openingAnimation: 'zoom',
    layoutStyle: 'side_by_side',
    coupleTransition: 'parallax_float',
    ornamentTransition: 'expand_line',
    panelTransition: 'staggered_slide',
    photoColorFilter: 'noir_bw',
    galleryLayout: 'film_strip',
    monogramStyle: 'minimal_hex',
    wishesStyle: 'chat_bubbles',
    dividerShape: 'slant',
    cardStyler: { borderRadius: 0, backdropBlur: 16, shadowLevel: 'none', borderWidth: 1 },
    guestTouchFx: 'sparkle_trail',
    livingMotion: { floatingIntensity: 'dynamic', breathingBloom: false, shimmerGlow: true, entrancePhysics: 'snappy' }
  },
  {
    name: 'Rose Gold Romance',
    colors: { bg: '#FFF9F9', paper: '#FFFFFF', fg: '#332227', muted: '#8F6E78', accent: '#B76E79', accentSoft: '#FADADD', cover: '#4A2832' },
    opacities: { bg: 100, paper: 85, accent: 100, accentSoft: 100, cover: 65 },
    fonts: { display: '"Playfair Display", serif', script: '"Great Vibes", cursive', body: '"Outfit", sans-serif', letterSpacing: '0.04em' },
    ornamentStyle: 'botanical',
    particleEffect: 'petals',
    coverStyle: 'arch',
    openingAnimation: 'wax_seal',
    layoutStyle: 'arch',
    coupleTransition: 'scale_up',
    ornamentTransition: 'unfurl',
    panelTransition: 'pop_in',
    photoColorFilter: 'warm_vintage',
    galleryLayout: 'masonry',
    monogramStyle: 'royal_laurel',
    wishesStyle: 'floating_cards',
    dividerShape: 'botanical',
    cardStyler: { borderRadius: 12, backdropBlur: 8, shadowLevel: 'medium', borderWidth: 1 },
    guestTouchFx: 'petal_burst',
    livingMotion: { floatingIntensity: 'medium', breathingBloom: true, shimmerGlow: true, entrancePhysics: 'smooth_spring' }
  },
  {
    name: 'Batik Kraton',
    colors: { bg: '#1A120B', paper: '#2B1B14', fg: '#F5EBE0', muted: '#D5BDAF', accent: '#D4A373', accentSoft: '#4A3525', cover: '#140C07' },
    opacities: { bg: 100, paper: 90, accent: 100, accentSoft: 100, cover: 80 },
    fonts: { display: '"Cinzel", serif', script: '"Alex Brush", cursive', body: '"Lora", serif', letterSpacing: '0.05em' },
    ornamentStyle: 'batik',
    particleEffect: 'gold_dust',
    coverStyle: 'classic',
    openingAnimation: 'curtain',
    layoutStyle: 'stacked',
    coupleTransition: 'meet_middle',
    ornamentTransition: 'expand_line',
    panelTransition: 'flip_3d',
    photoColorFilter: 'kodak_film',
    galleryLayout: 'grid',
    monogramStyle: 'victorian_crest',
    wishesStyle: 'editorial_vintage',
    dividerShape: 'crown',
    cardStyler: { borderRadius: 6, backdropBlur: 10, shadowLevel: 'dramatic_3d', borderWidth: 1 },
    guestTouchFx: 'sparkle_trail',
    livingMotion: { floatingIntensity: 'subtle', breathingBloom: true, shimmerGlow: true, entrancePhysics: 'cinematic_slow' }
  },
]

// Photographer Filter Presets (Color Grading)
export const photoFilterMap = {
  none: { name: 'Asli (No Filter)', css: 'none', desc: 'Warna natural kamera' },
  warm_vintage: { name: 'Warm Vintage', css: 'sepia(0.22) contrast(1.08) brightness(0.97) saturate(1.15)', desc: 'Nuansa hangat keemasan klasik' },
  noir_bw: { name: 'Noir B&W Fashion', css: 'grayscale(1) contrast(1.22) brightness(0.95)', desc: 'Hitam putih majalah mode mewah' },
  champagne_glow: { name: 'Champagne Glow', css: 'brightness(1.05) contrast(1.02) saturate(1.08)', desc: 'Cahaya lembut champagne berseri' },
  kodak_film: { name: 'Kodak 35mm Analog', css: 'contrast(1.12) saturate(1.22) hue-rotate(-4deg) brightness(0.98)', desc: 'Sentuhan film analog estetik' },
  pastel_dream: { name: 'Pastel Dream', css: 'contrast(0.94) brightness(1.06) saturate(0.92)', desc: 'Lembut romantis berkabut' },
}

// Photographer Gallery Layouts
export const galleryLayoutOptions = [
  { id: 'grid', name: 'Grid Kotak Klasik', desc: '3 kolom persegi simetris' },
  { id: 'masonry', name: 'Editorial Magazine Collage', desc: 'Kolase asimetris ala majalah mode' },
  { id: 'film_strip', name: 'Cinematic Film Strip', desc: 'Pita klise film bergulir horizontal' },
  { id: 'carousel', name: 'Featured Showcase Hero', desc: 'Foto utama besar + baris thumbnail' },
]

// Curated Typography Options
export const displayFontOptions = [
  { name: 'Playfair Display', font: '"Playfair Display", serif', tag: 'Elegan Modern' },
  { name: 'Cinzel Decorative', font: '"Cinzel", serif', tag: 'Mewah Kerajaan' },
  { name: 'Cormorant Garamond', font: '"Cormorant Garamond", serif', tag: 'Klasik Editorial' },
  { name: 'DM Serif Display', font: '"DM Serif Display", serif', tag: 'Romantis Bersih' },
  { name: 'Syne Vogue', font: '"Syne", sans-serif', tag: 'Avant-Garde' },
  { name: 'Italiana', font: '"Italiana", serif', tag: 'High Fashion' },
  { name: 'Bodoni Moda', font: '"Bodoni Moda", serif', tag: 'Luxury Magazine' },
  { name: 'Montserrat Classic', font: '"Montserrat", sans-serif', tag: 'Modern Bold' },
]

export const scriptFontOptions = [
  { name: 'Alex Brush', font: '"Alex Brush", cursive', tag: 'Kaligrafi Anggun' },
  { name: 'Great Vibes', font: '"Great Vibes", cursive', tag: 'Lengkung Mewah' },
  { name: 'Pinyon Script', font: '"Pinyon Script", cursive', tag: 'Royal Vintage' },
  { name: 'Allura Script', font: '"Allura", cursive', tag: 'Modern Signature' },
  { name: 'Dancing Script', font: '"Dancing Script", cursive', tag: 'Ceria Hangat' },
  { name: 'Parisienne', font: '"Parisienne", cursive', tag: 'French Romance' },
  { name: 'Sacramento', font: '"Sacramento", cursive', tag: 'Minimal Script' },
]

export const bodyFontOptions = [
  { name: 'Plus Jakarta Sans', font: '"Plus Jakarta Sans", sans-serif', tag: 'Standar Aruna (Sangat Terbaca)' },
  { name: 'Lora Serif', font: '"Lora", serif', tag: 'Sastra Romantis' },
  { name: 'Outfit Modern', font: '"Outfit", sans-serif', tag: 'Clean Geometric' },
  { name: 'Inter Clean', font: '"Inter", sans-serif', tag: 'Minimalis Tajam' },
  { name: 'Merriweather', font: '"Merriweather", serif', tag: 'Buku Elegan' },
  { name: 'Poppins', font: '"Poppins", sans-serif', tag: 'Modern Friendly' },
]

// Default Reorderable Sections
export const initialSectionList = [
  { id: 'hero', name: 'Header Utama & Nama Mempelai', defaultTitle: 'Walimatul Urs', visible: true },
  { id: 'greeting', name: 'Salam Pembuka & Kutipan / Ayat', defaultTitle: 'Surat Cinta', visible: true },
  { id: 'couple', name: 'Profil Kedua Mempelai & Orang Tua', defaultTitle: 'Pasangan Mempelai', visible: true },
  { id: 'countdown', name: 'Hitung Mundur Waktu Hari-H', defaultTitle: 'Menuju Hari Bahagia', visible: true },
  { id: 'events', name: 'Rangkaian Jadwal Acara (Akad & Resepsi)', defaultTitle: 'Rangkaian Acara', visible: true },
  { id: 'story', name: 'Cerita Kisah Cinta & Voice Note', defaultTitle: 'Cerita Kami', visible: true },
  { id: 'gallery', name: 'Galeri Foto Kenangan & Video', defaultTitle: 'Momen Bahagia', visible: true },
  { id: 'dresscode', name: 'Panduan Busana & Warna (Dresscode)', defaultTitle: 'Dresscode Acara', visible: true },
  { id: 'live', name: 'Siaran Langsung (Live Stream)', defaultTitle: 'Live Streaming', visible: true },
  { id: 'rsvp', name: 'Formulir Konfirmasi Kehadiran (RSVP)', defaultTitle: 'Konfirmasi Kehadiran', visible: true },
  { id: 'wishes', name: 'Buku Tamu & Ucapan Doa Restu', defaultTitle: 'Doa & Ucapan', visible: true },
  { id: 'gift', name: 'Amplop Digital & Tanda Kasih', defaultTitle: 'Wedding Gift', visible: true },
  { id: 'checkin', name: 'Kartu Akses QR Check-in', defaultTitle: 'QR Akses Masuk', visible: true },
  { id: 'closer', name: 'Ucapan Terima Kasih & Penutup', defaultTitle: 'Matur Nuwun', visible: true },
]
